"""Daily shutdown — the evening "close the loop" pass (Phase 2).

Mirror image of the morning briefing: at day's end, read today's time-blocks from the
current week's chief-of-staff proposals and write two artifacts —

  * ``shutdown/<date>.md`` — today's blocks with a "mark done?" checklist prompt, so the
    evening review is one glance and a couple of edits.
  * ``tomorrow.md`` — tomorrow's top-3 blocks (a tee-up for the next morning).

All deterministic file IO over
``workspaces/personal/chief-of-staff/proposals/<week>.calendar.json`` (same layout as
``weekly_plan.py``). Read-only against the calendar — this proposes/records, never writes
events. ``run_day_end`` and ``day_end_section`` degrade gracefully and never raise.
"""

from __future__ import annotations

import datetime
import json
from pathlib import Path

from agentos.core import config


def _week_for(date: datetime.date) -> str:
    iso = date.isocalendar()
    return f"{iso[0]}-W{iso[1]:02d}"


def _proposals_path(week: str) -> Path:
    return config.AGENTOS_ROOT / config.cos_dir() / "proposals" / f"{week}.calendar.json"


def _shutdown_path(date_str: str) -> Path:
    return config.AGENTOS_ROOT / config.cos_dir() / "shutdown" / f"{date_str}.md"


def _tomorrow_path() -> Path:
    return config.AGENTOS_ROOT / config.cos_dir() / "tomorrow.md"


def _load_proposals(week: str) -> list[dict]:
    """Read a week's blocks; ``[]`` when missing/corrupt (offline-safe)."""
    p = _proposals_path(week)
    if not p.exists():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return []
    return data if isinstance(data, list) else []


def _blocks_on(date_str: str) -> list[dict]:
    """Today's blocks (start date == date_str), sorted by start time. Spans the right week."""
    try:
        date = datetime.date.fromisoformat(date_str)
    except Exception:  # noqa: BLE001
        return []
    blocks = _load_proposals(_week_for(date))
    today = [b for b in blocks if str(b.get("start", "")).startswith(date_str)]
    today.sort(key=lambda b: b.get("start", ""))
    return today


_STATUS_MARK = {"created": "✅", "approved": "☑️"}


def _fmt_time(ts: str) -> str:
    return str(ts)[11:16] if len(str(ts)) >= 16 else str(ts)


def _block_line(b: dict, *, checkbox: bool = False) -> str:
    start, end = _fmt_time(b.get("start", "")), _fmt_time(b.get("end", ""))
    area = b.get("focus_area", "")
    summary = b.get("summary", "(block)")
    if checkbox:
        return f"- [ ] {start}–{end} **{summary}** _({area})_"
    mark = _STATUS_MARK.get(b.get("status", "proposed"), "◻️")
    return f"- {mark} {start}–{end} **{summary}** _({area})_"


def _render_shutdown(date_str: str, today: list[dict]) -> str:
    out = [f"# Daily shutdown — {date_str}", ""]
    if not today:
        out.append("- No blocks were scheduled today — nothing to review.")
        out.append("")
        out.append("**Reflection:** What got done anyway? Anything to carry into tomorrow?")
        return "\n".join(out) + "\n"

    out.append("## Today's blocks — mark what happened")
    out.append("_Check the ones you actually did; strike or note the ones that slipped._")
    out.append("")
    for b in today:
        out.append(_block_line(b, checkbox=True))
    out.append("")
    out.append("## Close the loop")
    out.append("- **Did the plan match reality?** Note any block that didn't happen and why.")
    out.append("- **Carry-over:** anything to push to tomorrow or next week?")
    out.append("- **One win:** what's the single thing that made today count?")
    out.append("")
    out.append(
        "---\n_Generated by `agentos day-end`. To record approvals/creations, edit the "
        "block `status` in this week's `proposals/<week>.calendar.json`._"
    )
    return "\n".join(out) + "\n"


def _render_tomorrow(tomorrow_str: str, blocks: list[dict]) -> str:
    out = [f"# Tomorrow — {tomorrow_str}", ""]
    if not blocks:
        out.append("- No blocks scheduled for tomorrow yet.")
        out.append("- If that's wrong, check this week's plan (or run the weekly planner).")
        out.append("")
        out.append("---\n_Generated by `agentos day-end`._")
        return "\n".join(out) + "\n"

    top3 = blocks[:3]
    out.append("## Top 3 for tomorrow")
    for b in top3:
        out.append(_block_line(b))
    if len(blocks) > 3:
        out.append("")
        out.append(f"_…plus {len(blocks) - 3} more block(s) on the calendar._")
    out.append("")
    out.append("**Tomorrow's #1:** " + top3[0].get("summary", "(block)") + ".")
    out.append("")
    out.append("---\n_Generated by `agentos day-end`. Tee-up for the morning brief._")
    return "\n".join(out) + "\n"


def run_day_end(date_str: str) -> dict:
    """Write ``shutdown/<date>.md`` + ``tomorrow.md`` for the given date. Deterministic.

    Returns a summary dict (counts + paths). Never raises — on any failure it records the
    error and returns what it could so a cron/cli caller degrades gracefully.
    """
    result: dict = {
        "date": date_str,
        "today_count": 0,
        "tomorrow_count": 0,
        "shutdown_path": None,
        "tomorrow_path": None,
        "errors": [],
    }
    try:
        today = _blocks_on(date_str)
        result["today_count"] = len(today)

        shutdown_path = _shutdown_path(date_str)
        shutdown_path.parent.mkdir(parents=True, exist_ok=True)
        shutdown_path.write_text(_render_shutdown(date_str, today), encoding="utf-8")
        result["shutdown_path"] = str(shutdown_path)

        try:
            tomorrow = datetime.date.fromisoformat(date_str) + datetime.timedelta(days=1)
        except Exception:  # noqa: BLE001
            tomorrow = datetime.date.today() + datetime.timedelta(days=1)
        tomorrow_str = tomorrow.isoformat()
        tomorrow_blocks = _blocks_on(tomorrow_str)
        result["tomorrow_count"] = len(tomorrow_blocks)

        tomorrow_path = _tomorrow_path()
        tomorrow_path.parent.mkdir(parents=True, exist_ok=True)
        tomorrow_path.write_text(
            _render_tomorrow(tomorrow_str, tomorrow_blocks), encoding="utf-8"
        )
        result["tomorrow_path"] = str(tomorrow_path)
    except Exception as ex:  # noqa: BLE001 — never crash a shutdown run
        result["errors"].append(str(ex))
    return result


def day_end_section(date_str: str) -> str:
    """Briefing/CLI markdown: today's blocks + a mark-done prompt. Offline-safe."""
    try:
        today = _blocks_on(date_str)
    except Exception:  # noqa: BLE001
        return "- (shutdown data unavailable)"
    if not today:
        return "- No blocks scheduled today — nothing to close out."
    lines = [_block_line(b, checkbox=True) for b in today]
    lines.append("")
    lines.append("_Check what happened; note anything that slipped._")
    return "\n".join(lines)
